- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
    - name: Set timezone to  SP/BR
      timezone:
        name: America/Sao_Paulo    
        
        
- hosts: controllers
  remote_user: vagrant
  tasks:
    - name: Criando Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR ANSIBLE CONTROLLER
        create: yes
        

- hosts: databases
  remote_user: vagrant
  become: yes
  tasks:
    - name: Criando Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR DE BANCO DE DADOS MYSQL
        create: yes

    - name: Especifica o usuario root antes de instalar
      debconf: name='mysql-server' question='mysql-server/root_password' value='123' vtype='password'

    - name: Confirmando a Senha de Administrador do Mysql
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='123' vtype='password'
        
    - name: Instalando MYSQL
      apt: 
        state: present
        update_cache: yes
        pkg: 
          - mysql-server 
          - python-pymysql
          
    - name: Criando um database
      mysql_db: 
       name: wordpress 
       state: present
       login_user: root
       login_password: 123
    
    - name: Criando o usuario do banco
      mysql_user: 
        name: wordpress
        password: impacta
        priv: '*.*:ALL'
        state: present
        host: 172.17.177.22
        login_user: root
        login_password: 123


    - name: Liberando o MySql para conexões
      lineinfile: 
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: bind-address = 0.0.0.0
      notify: 
        - restart mysql
        
    - name: restart mysql
      service: 
        name: restart mysql     
        state: restarted
         
- hosts: webservers
  remote_user: vagrant
  become: yes
  tasks:
    - name: Criando Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR DO BLOG WORDPRESS
        create: yes
    - name: Instalando Apache e PHP
      apt: 
       state: present
       update_cache: yes
       pkg: 
         - apache2
         - php-curl
         - php-gd
         - php-mbstring
         - php-xml
         - php-xmlrpc
         - php-soap
         - php-intl
         - php-zip
         - php
         - libapache2-mod-php
         - php-mysql
         
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: restart mysql
      service:
        name: mysql
        state: restarted 
